"""create security_scans table

Revision ID: f8cf7e126a1e
Revises: 2435fafd8795
Create Date: 2026-08-05 22:32:10.540994

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8cf7e126a1e"
down_revision: Union[str, Sequence[str], None] = "2435fafd8795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("extension", sa.String(length=20), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("security_score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scan_details", sa.JSON(), nullable=True),
        sa.Column("threat_type", sa.String(length=50), nullable=False),
        sa.Column("scan_duration_ms", sa.Integer(), nullable=False),
        sa.Column("scanner_version", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            threat_type IN (
                'NONE',
                'MALWARE',
                'MACRO',
                'EXECUTABLE',
                'SUSPICIOUS',
                'UNKNOWN'
            )
            """,
            name="chk_security_threat",
        ),
        sa.CheckConstraint(
            "risk_level IN ('SAFE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name="chk_risk_level",
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'SCANNING', 'COMPLETED', 'FAILED')",
            name="chk_security_status",
        ),
        sa.CheckConstraint(
            "security_score BETWEEN 0 AND 100", name="chk_security_score"
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"], ["upload_history.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_scans_id"), "security_scans", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_security_scans_id"), table_name="security_scans")
    op.drop_table("security_scans")
    # ### end Alembic commands ###
